import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/theme";
import { App } from "@/App"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Technical Assignment by Elena GS",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        {/* All the components inside this ThemeProvider will use this specific theme */}
        <App />
      </ThemeProvider>
    </html>
  );
}
